export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REGUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REGUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REGUEST_ROBOTS_FAILED';